name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Find APK
      run: |
        cp app/build/outputs/apk/debug/app-debug.apk $HOME/
        echo ""
        echo ""
        echo "---------------->>"
        find ~ -name "*.apk"
        echo "<<----------------"
        echo ""
        echo ""
        
      
    - name: Upload APK
      uses: actions/upload-artifact@v3  # Aktualisiert auf v3
      with:
        name: app-debug.apk
        path: /home/runner/app-debug.apk
        if-no-files-found: error
